### ISSUE TITLE
Activate travis-ci?

### ISSUE THREAD

**Issue by donv** [gtd/csv_builder#17]
Hi!

I see there are some specs and there is a travis-ci config, but it looks like travis is not activated.

Maybe activate it?  I can help setting it up and maintain it if needed.

**Comment by donv** [comment]
I think the way forward would be GitHub Actions.  I can submit a PR for this if you like.

**Comment by gtd** [comment]
Yes I was thinking the same, PR is definitely welcome.

**Comment by donv** [comment]
@gtd Are you able to run the tests in your environment?  If so, what version of Ruby and Rails are you using?

**Comment by gtd** [comment]
I have no run specs on my current machine and I see there are a lot of compatibility issues with newer versions of various gems.  I'm attempting to put some pessimistic constraints in to see if I can get them running again.

**Comment by donv** [comment]
I think the gem is OK in itself, and that the problems are mostly around the specs and gem setup.  I have been using the gem without problems for many years on the newest Ruby/Rails combos.

**Comment by gtd** [comment]
Okay I got specs running on ruby 2.5.7 and rails 4.2.11.3.  Changes pushed to master.  Could you let me know if it works for you on a clean bundle install?

**Comment by gtd** [comment]
Alright, I have it working through all currently supported rails versions.  Github Actions is set up to run the specs on rails 6.1.x for ruby 2.5, 2.6, and 2.7.

Next steps would be:

* Get specs running on ruby 3.0.0
* Figure out how to add different Rails versions to the matrix tests
